before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/vipd
    id: "vipd"
    binary: vipd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -X github.com/ehazlett/vipd/version.GitCommit={{ .FullCommit }} -X github.com/ehazlett/vipd/version.Version={{ .RawVersion }}
archives:
  - id: vipd
    builds:
      - vipd
    name_template: "vipd_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: ehazlett
    name: vipd
  draft: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
